from __future__ import annotations

import json
from pathlib import Path

from memdex.cli import app
from tests.conftest import tree_hash, write_config


def run(runner, *args, **kwargs):
    result = runner.invoke(app, list(args), **kwargs)
    assert result.exit_code == 0, result.output
    return result


class TestDryRun:
    def test_writes_nothing_at_all(self, runner, demo_project: Path):
        before = tree_hash(demo_project, "MEMORY.md", "memory", ".claude")
        result = run(runner, "run", "--dry-run")
        assert tree_hash(demo_project, "MEMORY.md", "memory", ".claude") == before
        assert "Nothing was written" in result.output

    def test_shows_the_proposed_changes_and_metrics(self, runner, demo_project: Path):
        result = run(runner, "run", "--dry-run")
        assert "Proposed changes" in result.output
        assert "write" in result.output and "memory/" in result.output
        assert "Before:" in result.output

    def test_never_creates_the_vector_store(self, runner, demo_project: Path):
        run(runner, "run", "--dry-run")
        chroma = demo_project / ".memdex" / "chroma"
        assert not chroma.exists() or not any(chroma.iterdir())

    def test_records_no_activity(self, runner, demo_project: Path):
        run(runner, "run", "--dry-run")
        result = run(runner, "history")
        assert "No activity recorded yet" in result.output

    def test_compact_dry_run_ends_with_the_apply_hint(self, runner, demo_project: Path):
        run(runner, "run")
        result = run(runner, "compact", "--dry-run")
        assert "Memory Analysis" in result.output
        assert "Run without --dry-run to apply." in result.output


class TestSearch:
    def test_finds_the_right_memory(self, runner, demo_project: Path):
        run(runner, "run")
        result = run(runner, "search", "why did we choose chroma over elasticsearch")
        assert "Chroma selection" in result.output
        assert "memory/decisions/chroma-selection.md" in result.output
        assert "Score:" in result.output

    def test_top_k_limits_results(self, runner, demo_project: Path):
        run(runner, "run")
        result = run(runner, "search", "database", "--top-k", "2")
        assert "2 memories found" in result.output

    def test_category_filter(self, runner, demo_project: Path):
        run(runner, "run")
        result = run(runner, "search", "postgres", "--category", "architecture", "-k", "5")
        assert "conventions" not in result.output

    def test_without_an_index_it_explains_what_to_do(self, runner, demo_project: Path):
        result = runner.invoke(app, ["search", "anything"])
        assert result.exit_code == 1
        assert "memdex run" in result.output

    def test_warns_when_the_embedder_changed(self, runner, demo_project: Path):
        run(runner, "run")
        registry = demo_project / ".memdex" / "metadata" / "memories.json"
        data = json.loads(registry.read_text(encoding="utf-8"))
        data["embedder_fingerprint"] = "local:onnx-minilm-l6-v2:384"
        registry.write_text(json.dumps(data), encoding="utf-8")
        result = run(runner, "search", "database")
        assert "memdex index" in result.output


class TestCompact:
    def test_reports_every_category_of_finding(self, runner, demo_project: Path):
        run(runner, "run")
        result = run(runner, "compact", "--dry-run")
        for label in ("Duplicates", "Redundant sections", "Large sections", "Potentially obsolete"):
            assert label in result.output

    def test_flags_the_obsolete_memory(self, runner, demo_project: Path):
        run(runner, "run")
        result = run(runner, "compact", "--dry-run")
        assert "Session storage (deprecated)" in result.output

    def test_obsolete_memories_are_never_deleted(self, runner, demo_project: Path):
        run(runner, "run")
        run(runner, "compact")
        assert list(demo_project.glob("memory/*/session-storage-deprecated.md"))


class TestIndexCommand:
    def test_regenerates_only_the_index(self, runner, demo_project: Path):
        run(runner, "run")
        tree_before = tree_hash(demo_project, "memory")
        (demo_project / "MEMORY.md").write_text("<!-- generated by memdex -->\nstale\n", "utf-8")

        run(runner, "index")

        assert tree_hash(demo_project, "memory") == tree_before
        assert "# Memory Index" in (demo_project / "MEMORY.md").read_text(encoding="utf-8")

    def test_refuses_to_overwrite_unmigrated_notes(self, runner, demo_project: Path):
        result = runner.invoke(app, ["index"])
        assert result.exit_code == 1
        assert "memdex run" in result.output
        assert "# Project Memory" in (demo_project / "MEMORY.md").read_text(encoding="utf-8")

    def test_reembeds_an_edited_memory(self, runner, demo_project: Path):
        run(runner, "run")
        target = next(demo_project.glob("memory/*/database*.md"))
        target.write_text(
            target.read_text(encoding="utf-8")
            + "\nWe also run a read replica in Frankfurt.\n",
            encoding="utf-8",
        )
        result = run(runner, "index")
        assert "local embedding" in result.output

        # The edited text must be what is actually stored and searched.
        from memdex.config import load_config
        from memdex.store import VectorStore

        store = VectorStore(load_config(demo_project))
        documents = store.memories.get(include=["documents"])["documents"]
        assert any("read replica in Frankfurt" in doc for doc in documents)
        assert "Database" in run(runner, "search", "read replica Frankfurt").output


class TestStatusAndHistory:
    def test_status_before_and_after_a_run(self, runner, demo_project: Path):
        assert "never" in run(runner, "status").output
        run(runner, "run")
        output = run(runner, "status").output
        assert "Vectors" in output and "saved" in output

    def test_history_lists_runs_with_savings(self, runner, demo_project: Path):
        run(runner, "run")
        run(runner, "compact")
        output = run(runner, "history").output
        assert output.count("run") >= 1 and "compact" in output
        assert "%" in output

    def test_history_is_empty_before_any_run(self, runner, demo_project: Path):
        assert "No activity recorded yet" in run(runner, "history").output


class TestDoctor:
    def test_passes_on_a_healthy_project(self, runner, demo_project: Path):
        run(runner, "run")
        output = run(runner, "doctor").output
        assert "ChromaDB" in output and "Vector store" in output
        assert "✗" not in output

    def test_fails_when_the_llm_is_misconfigured(self, runner, demo_project: Path):
        write_config(demo_project)
        config = demo_project / ".memdex" / "config.yaml"
        config.write_text(
            config.read_text(encoding="utf-8").replace(
                "llm:\n  enabled: false", "llm:\n  enabled: true"
            ),
            encoding="utf-8",
        )
        result = runner.invoke(app, ["doctor"])
        assert result.exit_code == 1
        assert "llm.model" in result.output


class TestRestore:
    def test_round_trip_restores_the_original_bytes(self, runner, demo_project: Path):
        before = tree_hash(demo_project, "MEMORY.md", "memory")
        run(runner, "run")
        assert tree_hash(demo_project, "MEMORY.md", "memory") != before

        run(runner, "restore", "--latest", "--yes")
        assert tree_hash(demo_project, "MEMORY.md", "memory") == before

    def test_removes_files_memdex_created(self, runner, demo_project: Path):
        run(runner, "run")
        assert list(demo_project.glob("memory/*/*.md"))
        run(runner, "restore", "--latest", "--yes")
        assert not list(demo_project.glob("memory/*/*.md"))

    def test_takes_its_own_backup_first(self, runner, demo_project: Path):
        run(runner, "run")
        run(runner, "restore", "--latest", "--yes")
        reasons = [
            json.loads((d / "manifest.json").read_text(encoding="utf-8"))["reason"]
            for d in (demo_project / ".memdex" / "backups").iterdir()
        ]
        assert any(r.startswith("pre-restore") for r in reasons)

    def test_restore_is_recorded(self, runner, demo_project: Path):
        run(runner, "run")
        run(runner, "restore", "--latest", "--yes")
        assert "restore" in run(runner, "history").output

    def test_without_backups_it_says_so(self, runner, demo_project: Path):
        result = runner.invoke(app, ["restore", "--latest"])
        assert result.exit_code == 1
        assert "no backups" in result.output.lower()


class TestClean:
    def test_clears_the_index_but_keeps_the_files(self, runner, demo_project: Path):
        run(runner, "run")
        tree = tree_hash(demo_project, "MEMORY.md", "memory")

        result = run(runner, "clean", "--yes")

        assert "Cleared" in result.output
        assert tree_hash(demo_project, "MEMORY.md", "memory") == tree
        assert not (demo_project / ".memdex" / "metadata" / "memories.json").exists()
        assert (demo_project / ".memdex" / "config.yaml").exists()

    def test_keeps_backups(self, runner, demo_project: Path):
        run(runner, "run")
        backups = len(list((demo_project / ".memdex" / "backups").iterdir()))
        run(runner, "clean", "--yes")
        assert len(list((demo_project / ".memdex" / "backups").iterdir())) == backups

    def test_records_that_the_user_cleaned(self, runner, demo_project: Path):
        run(runner, "run")
        run(runner, "clean", "--yes")
        output = run(runner, "history").output
        assert "clean" in output
        assert "memory data was reset, log kept" in output

    def test_a_later_run_rebuilds(self, runner, demo_project: Path):
        run(runner, "run")
        run(runner, "clean", "--yes")
        run(runner, "run")
        assert "Chroma selection" in run(runner, "search", "chroma decision").output

    def test_all_requires_confirmation(self, runner, demo_project: Path):
        run(runner, "run")
        result = runner.invoke(app, ["clean", "--all"])
        assert result.exit_code == 1
        assert (demo_project / ".memdex").exists()

    def test_all_removes_everything_but_the_memory_files(self, runner, demo_project: Path):
        run(runner, "run")
        tree = tree_hash(demo_project, "MEMORY.md", "memory")
        run(runner, "clean", "--all", "--yes")
        assert not (demo_project / ".memdex").exists()
        assert tree_hash(demo_project, "MEMORY.md", "memory") == tree
