"""Core data structures.

Everything here is a plain dataclass: the pipeline builds them, renderers read
them. Paths are project-root-relative unless a field says otherwise.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Literal

# Fixed order — used for index sections, categorizer tie-breaks and UI grouping.
CATEGORIES: tuple[str, ...] = (
    "architecture",
    "decisions",
    "development",
    "projects",
    "conventions",
    "infrastructure",
    "reference",
    "general",
)

INDEX_MARKER = "<!-- generated by memdex"


class SourceMode(str, Enum):
    MANAGED = "managed"
    READONLY = "readonly"


class PlanMode(str, Enum):
    RUN = "run"
    COMPACT = "compact"
    INDEX = "index"


@dataclass
class SourceFile:
    path: Path  # relative to project root
    mode: SourceMode
    raw_text: str
    frontmatter: dict | None = None
    is_generated_index: bool = False
    is_adopted_doc: bool = False


@dataclass
class DocNode:
    """A node of the markdown heading tree. level 0 is the document root."""

    level: int
    heading: str | None
    own_text: str
    children: list[DocNode] = field(default_factory=list)
    line_start: int = 0
    line_end: int = 0


@dataclass
class MemoryUnit:
    title: str
    body: str
    source_file: Path
    source_mode: SourceMode = SourceMode.MANAGED
    id: str | None = None
    breadcrumb: tuple[str, ...] = ()
    # The heading the whole source file sits under, used to name a readonly file
    # in the index (where one entry stands for the entire document).
    document_title: str = ""
    line_start: int = 0
    line_end: int = 0
    category: str = "general"
    description: str = ""
    importance: float = 0.5
    token_count: int = 0
    content_hash: str = ""
    dedupe_key: str = ""
    provenance: str = ""
    shadowed_by: str | None = None
    merged_from: list[str] = field(default_factory=list)
    obsolete: bool = False
    frontmatter_locked: bool = False

    @property
    def is_managed(self) -> bool:
        return self.source_mode is SourceMode.MANAGED

    @property
    def is_live(self) -> bool:
        """Units that reach the index, the output tree and the vector store."""
        return self.shadowed_by is None


@dataclass
class PlannedDoc:
    unit_id: str
    path: Path
    rendered: str


@dataclass
class FileOp:
    path: Path
    action: Literal["write", "overwrite", "delete"]
    reason: str = ""


@dataclass
class CompactAnalysis:
    # "current" and "optimized" measure context cost: what an assistant loads
    # before (the whole memory) versus after (the index alone).
    current_tokens: int = 0
    optimized_tokens: int = 0
    # Stored memory before and after dedupe/compression — the knowledge itself.
    content_before: int = 0
    content_after: int = 0
    tokens_estimated: bool = True
    exact_dupes: list[tuple[str, str]] = field(default_factory=list)
    near_dupes: list[tuple[str, str, float]] = field(default_factory=list)
    similar_pairs: list[tuple[str, str, float]] = field(default_factory=list)
    large_sections: list[tuple[str, int]] = field(default_factory=list)
    obsolete: list[str] = field(default_factory=list)
    planned_files: list[Path] = field(default_factory=list)

    @property
    def tokens_saved(self) -> int:
        return max(0, self.current_tokens - self.optimized_tokens)

    @property
    def pct_saved(self) -> float:
        if self.current_tokens <= 0:
            return 0.0
        return 100.0 * self.tokens_saved / self.current_tokens

    @property
    def content_saved(self) -> int:
        return max(0, self.content_before - self.content_after)

    @property
    def content_pct_saved(self) -> float:
        if self.content_before <= 0:
            return 0.0
        return 100.0 * self.content_saved / self.content_before


@dataclass
class RunReport:
    mode: PlanMode = PlanMode.RUN
    sources_found: int = 0
    files_scanned: int = 0
    units_parsed: int = 0
    exact_duplicates: int = 0
    near_duplicates: int = 0
    units_final: int = 0
    files_written: int = 0
    files_deleted: int = 0
    # Context cost: what an assistant loaded before, and loads now.
    tokens_before: int = 0
    tokens_after: int = 0
    # Stored memory before and after dedupe/compression.
    content_before: int = 0
    content_after: int = 0
    tokens_estimated: bool = True
    embeddings_generated: int = 0
    embeddings_skipped: int = 0
    vector_count: int = 0
    optimizer_label: str = "Deterministic"
    embedder_label: str = "Local"
    dry_run: bool = False
    no_changes: bool = False
    backup_dir: Path | None = None
    warnings: list[str] = field(default_factory=list)

    @property
    def tokens_saved(self) -> int:
        return max(0, self.tokens_before - self.tokens_after)

    @property
    def pct_saved(self) -> float:
        if self.tokens_before <= 0:
            return 0.0
        return 100.0 * self.tokens_saved / self.tokens_before

    @property
    def content_saved(self) -> int:
        return max(0, self.content_before - self.content_after)

    @property
    def content_pct_saved(self) -> float:
        if self.content_before <= 0:
            return 0.0
        return 100.0 * self.content_saved / self.content_before

    @property
    def mode_label(self) -> str:
        return f"{self.optimizer_label} / {self.embedder_label}"


@dataclass
class MemoryPlan:
    mode: PlanMode
    units: list[MemoryUnit] = field(default_factory=list)
    docs: list[PlannedDoc] = field(default_factory=list)
    index_path: Path = Path("MEMORY.md")
    index_markdown: str = ""
    file_ops: list[FileOp] = field(default_factory=list)
    stale_ids: list[str] = field(default_factory=list)
    embed_ids: list[str] = field(default_factory=list)
    analysis: CompactAnalysis = field(default_factory=CompactAnalysis)
    report: RunReport = field(default_factory=RunReport)
    # Carried from the plan phase into the apply phase. Typed loosely to keep
    # models.py free of imports from the modules that build them.
    registry: Any = None
    paths: dict[str, Path] = field(default_factory=dict)

    @property
    def live_units(self) -> list[MemoryUnit]:
        return [u for u in self.units if u.is_live]

    @property
    def has_changes(self) -> bool:
        return bool(self.file_ops)


@dataclass
class SearchHit:
    id: str
    title: str
    path: Path
    category: str
    score: float
    snippet: str = ""


@dataclass
class BackupInfo:
    dir: Path
    created_at: str
    reason: str
    backed_up: list[Path] = field(default_factory=list)
    created: list[Path] = field(default_factory=list)

    @property
    def stamp(self) -> str:
        return self.dir.name


@dataclass
class AuditEvent:
    id: str
    event: str
    at: str
    summary: str = ""
    tokens_before: int = 0
    tokens_after: int = 0
    tokens_saved: int = 0
    pct_saved: float = 0.0
    files_written: int = 0
    units: int = 0
    vectors: int = 0
    mode_label: str = ""
